# Created by: Greg Becker <greg@codeconcepts.com>
# $FreeBSD$

PORTNAME=	svt
PORTVERSION=	1.0.0
CATEGORIES=	devel
MASTER_SITES=	http://codeconcepts.com/

MAINTAINER=	greg@codeconcepts.com
COMMENT=	System/storage verification tool

USE_BZIP2= 	yes
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

PLIST_FILES=	bin/svt
MAN1=		svt.1
MANCOMPRESSED=	no

.include <bsd.port.mk>
